root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && tailwindcss -i web/input.css -o web/static/main.css --minify && go build -o ./tmp/bin/dashboard ./cmd/dashboard"
  entrypoint = "./tmp/bin/dashboard"
  include_ext = ["go", "templ", "css"]
  exclude_regex = ["_test\\.go$", "_templ\\.go$"]
  exclude_dir = ["tmp", "web/static", ".git"]
  delay = 250
  stop_on_error = true
  send_interrupt = true
  kill_delay = "1s"

[log]
  time = true

[misc]
  clean_on_exit = true